<?php

namespace AnodioCoreTests;

use Anodio\Core\Helpers\StartHelper;

class TestCase extends \PHPUnit\Framework\TestCase
{
    protected function setUp(): void
    {
        if (!defined('BASE_PATH')) {
            $helper = new StartHelper();
            $helper->preload(__DIR__ . '/../');
        }
        require_once __DIR__ . '/../vendor/attributes.php';
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
